Add random number to key to avoid clashes on rendering
jeremybarbet/react-native-portalize pull request #9
Opened 2020-08-14 11:04 UTC by harveyappleton

Avoids issues where multiple portals on one screen can have same key (Date.now() is not sufficient on its own if rendering is fast enough).

Could look at using something like uuid instead of a random number to guarantee more uniqueness? 👍

2020-08-14 11:56 UTC, jeremybarbet commented
@harveyappleton Welcome to the open-source contribution world!

I totally agree, instead of trying to add a bit more of uniqueness each time, probably better to go directly with [uuid](https://github.com/uuidjs/uuid#readme) so we _shouldn't_ have any other problem moving forward.

Thanks for your PR!

2020-08-14 12:05 UTC, harveyappleton commented
Sounds good, happy to investigate this and do a new pull req with uuid integrated!

2020-08-16 12:25 UTC, harveyappleton commented
@jeremybarbet - rather than depending on another library (uuid), what about using a simple unique function? eg - https://gist.github.com/gordonbrander/2230317#gistcomment-3404537

2020-08-17 08:03 UTC, jeremybarbet commented
@harveyappleton Sure sounds good, let's try that!

2020-08-17 10:32 UTC, harveyappleton commented
@jeremybarbet I ended up using the UUID library because the gist i linked to there sadly didnt work as it also relied on Date.now() for randomness. Preliminary tests seem to show 5 portals on 1 react navigation screen working well! 

Appreciate any feedback as TS / OpenSource contribution goodness is new to me, think I've done it correctly but appreciate any comments :-) thanks guys

2020-08-17 11:19 UTC, jeremybarbet requested changes
Small changes but overall looks good to me!

2020-08-17 11:19 UTC, jeremybarbet commented on package.json
> +    "uuid": "^8.3.0"
Can we fix the version?

```suggestion
    "uuid": "8.3.0"
```

2020-08-17 11:19 UTC, jeremybarbet commented on src/Host.tsx
> +    const key = uuidv4();
For debugging purpose I think having portalize in the key would be useful.

```suggestion
    const key = `portalize_${uuidv4()}`;
```

2020-08-17 11:35 UTC, merged

2020-08-17 11:36 UTC, jeremybarbet commented
Thank you! I will release a new version so you can try it out :)

2020-08-17 14:52 UTC, edc123 commented
Oh I see it is time for me to magically reappear!

The github gist - as you mentioned - is just an extra letter of the alphabet away from "Date.now() + a random number", but I think this approach seemed "good enough".

Upon testing `1.0.6` in my app, I immediately got the following error: https://github.com/uuidjs/uuid#getrandomvalues-not-supported

When I follow these instructions to install the polyfill in my project - things work great and I don't seem to have any more issues with multiple instances. I'm going to run with it on my project.

Throwing it back to you peeps! (Through a new github issue... sorry)

2020-08-19 09:54 UTC, jeremybarbet commented
@edc123 Fix landed in `1.0.7`